### ISSUE TITLE
Update state at 60fps

### ISSUE THREAD

**Issue by AlexandruRoman** [solidjs-community/solid-three#1]
Amazing project! Currently thinking to switch from r3f to solid-three just because I'm assuming I can benefit from solid's performant updates. Looking at the example from playground, I see that you're updating the rotation of a mesh imperatively (`  useFrame(() => (mesh!.rotation.y += 0.01));`) instead of declaratively (using a signal for rotation) during a frame.

My question would be if you tested the performance for the declarative version before going with the imperative one (the one that's also recommended in r3f as React can't handle these frequent updates). Really curious if solid can handle that. Thanks

**Comment by ZanzyTHEbar** [comment]
Would be really nice to see this feature. With the new updates - let us know if you ever experiment with this.
