### ISSUE TITLE
Underlying `solid-js` package needs to be updated

### ISSUE THREAD

**Issue by yohgen** [solidjs-community/solid-three#2]
I originally discovered this issue while trying to set up `solid-three` and filed a bug report there: https://github.com/solidjs/solid/issues/1680#issue-1659286670

It appears that there are numerous bugs due to the fact that `solid-three` supplies its own version of `solid-js` in inline fashion, and attempting to use the latest `solid-js/web` version with older `solid-js` version supplied by `solid-three` leads to an API mismatch.

For example, the `use` function has been added to `solid-js/web`, which `solid-three` lacks, and transpiled code throws the following error: ~`The requested module 'solid-three' does not provide an export named 'use'`.

Here's a reproduction of the `use` bug: https://stackblitz.com/edit/solidjs-templates-p1lnyy?file=src/App.tsx

**Comment by ZanzyTHEbar** [comment]
This should now be fixed 💯 let us know if you see anything else that needs doing.

**Comment by yohgen** [comment]
@ZanzyTHEbar Works like a charm, thank you!
