### ISSUE TITLE
Solid Three does not work with a new Solid project

### ISSUE THREAD

**Issue by OmBudhiraja** [solidjs-community/solid-three#9]
I just created a new Solid project with ts template from https://github.com/solidjs/templates/ and added ```three``` and ```solid-three``` as deps and It give me the error when I use  ```<Canvas> { /** anything **/ } </Canvas>``` from solid-three

<img width="482" alt="Screenshot 2023-05-30 172535" src="https://github.com/solidjs-community/solid-three/assets/76561420/741bced4-6362-43c1-a9cf-73e937f0b81a">

**Comment by vorth** [comment]
You need to update the `vite.config.ts` to engage the universal renderer.  See:

https://github.com/solidjs-community/solid-three/blob/main/vite.config.ts

lines 39-57

Actually, you should start from the template mentioned in our README:

https://github.com/ZanzyTHEbar/solid-three-template

You can even create a GitHub Codespace from it.

**Comment by OmBudhiraja** [comment]
Okay, that works for me now :)

Closing the issue!
